# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('traffic-control', ['core', 'network'])
    module.source = [
      'model/traffic-control-layer.cc',
      'model/packet-filter.cc',
      'model/queue-disc.cc',
      'model/pfifo-fast-queue-disc.cc',
      'model/red-queue-disc.cc',
      'model/codel-queue-disc.cc',
      'helper/traffic-control-helper.cc',
      'helper/queue-disc-container.cc',
      'model/prio-queue-disc-filter.cc', ##add by myself###
      'model/fifo-queue-disc.cc',
      'model/cache.cc',
      'model/prio-queue-disc.cc',
      'model/prio-subqueue-disc.cc',
        ]

    module_test = bld.create_ns3_module_test_library('traffic-control')
    module_test.source = [
      'test/red-queue-disc-test-suite.cc',
      'test/codel-queue-disc-test-suite.cc',
      'test/prio-queue-disc-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'traffic-control'
    headers.source = [
      'model/traffic-control-layer.h',
      'model/packet-filter.h',
      'model/queue-disc.h',
      'model/pfifo-fast-queue-disc.h',
      'model/red-queue-disc.h',
      'model/codel-queue-disc.h',
      'helper/traffic-control-helper.h',
      'helper/queue-disc-container.h',
      'model/prio-queue-disc-filter.h', ##add by myself###
      'model/cache.h',
      'model/prio-queue-disc.h',
      'model/prio-subqueue-disc.h',
      'model/fifo-queue-disc.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    bld.ns3_python_bindings()

